services:
  backend:
    build: ./backend
    container_name: quiz_backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: host.docker.internal
      DB_USER: umesh
      DB_PASSWORD: umesh123
      DB_PORT:  3315
      DB_NAME: quiz_app
    volumes:
      - ./frontend:/frontend

volumes:
  db_data:
