version: '3.8'

services:
  db:
    image: mysql:8
    container_name: quiz_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: quiz_app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: quiz_backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root@123
      DB_NAME: quiz_app
    depends_on:
      - db
    volumes:
      - ./frontend:/app/frontend

volumes:
  db_data:
